spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    #    url: jdbc:sqlite::resource:db/skyeye.db
    username:
    password:
    #    driver-class-name: org.sqlite.JDBC
    url: jdbc:p6spy:sqlite::resource:db/iothub.db
    type: com.alibaba.druid.pool.DruidDataSource
    # druid相关配置
    druid:
      # 连接池初始化大小
      initial-size: 8
      # 最大活跃连接数
      max-active: 20
      # 最小空闲连接数
      min-idle: 1
      # 获取连接等待超时的时间
      max-wait: 60000
      # 间隔多久才进行一次检测，检测需要关闭的空闲连接，ms
      time-between-eviction-runs-millis: 60000
      validation-query: select 'x'
      # 配置过滤器，https://github.com/alibaba/druid/wiki/%E5%86%85%E7%BD%AEFilter%E7%9A%84%E5%88%AB%E5%90%8D
      filters: stat,slf4j,config

mqtt:
  ## 单机版--只需要把域名改为ip既可　
  hostUrl: tcp://192.168.50.10:1883
  username: admin
  password: public
  ## 服务端 clientId (发送端自己定义)
  clientId: iot_hub_192.168.50.10
  cleanSession: true
  reconnect: true
  timeout: 100
  keepAlive: 100
  defaultTopic: $SYS/brokers/+/clients/#
  qos: 0